/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.13.31
 * Contact: info@simsage.co.uk
 * Generated by: https://openapi-generator.tech
 */

/// CmDocumentNote : A note attached to a document.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CmDocumentNote {
    /// the main organisation (its guid id) for this source/crawler
    #[serde(rename = "organisationId")]
    pub organisation_id: String,
    /// the knowledge-base id of this context item, a guid-string
    #[serde(rename = "kbId")]
    pub kb_id: String,
    /// The unique URL of a document.
    #[serde(rename = "url")]
    pub url: String,
    /// The id of the note, starting at 1 note of 0 means create a new note
    #[serde(rename = "noteId")]
    pub note_id: i32,
    /// The text of the note
    #[serde(rename = "noteText")]
    pub note_text: String,
    /// The user's id
    #[serde(rename = "userId")]
    pub user_id: String,
    /// the email address of the user that made the change
    #[serde(rename = "email")]
    pub email: String,
    /// a unix-timestamp of the creation date-time of this record
    #[serde(rename = "created")]
    pub created: i64,
}

impl CmDocumentNote {
    /// A note attached to a document.
    pub fn new(organisation_id: String, kb_id: String, url: String, note_id: i32, note_text: String, user_id: String, email: String, created: i64) -> CmDocumentNote {
        CmDocumentNote {
            organisation_id,
            kb_id,
            url,
            note_id,
            note_text,
            user_id,
            email,
            created,
        }
    }
}


