/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.14.12
 * Contact: info@simsage.co.uk
 * Generated by: https://openapi-generator.tech
 */

/// CmSimilarDocument : A document that is similar to another document.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CmSimilarDocument {
    /// the url of the document that is similar
    #[serde(rename = "url")]
    pub url: String,
    /// the url-id of the document that is similar
    #[serde(rename = "urlId")]
    pub url_id: i32,
    /// how similar that document is (e.g. 1.0 = 100%)
    #[serde(rename = "similarity")]
    pub similarity: f32,
}

impl CmSimilarDocument {
    /// A document that is similar to another document.
    pub fn new(url: String, url_id: i32, similarity: f32) -> CmSimilarDocument {
        CmSimilarDocument {
            url,
            url_id,
            similarity,
        }
    }
}


