/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.13.31
 * Contact: info@simsage.co.uk
 * Generated by: https://openapi-generator.tech
 */

/// JsonMessage : A generic SimSage message class used throughout the system.  This class can be used to either send a success message (information) or an error message (error) but will never send you both at the same time.  Version might not always be set but is the version of the service-layer you're communicating with.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonMessage {
    /// A possible error message, empty if information is set
    #[serde(rename = "error")]
    pub error: String,
    /// An informational message, empty if error is set
    #[serde(rename = "information")]
    pub information: String,
    /// The version of this service (can be empty)
    #[serde(rename = "version")]
    pub version: String,
    /// The time this event occurred
    #[serde(rename = "time")]
    pub time: i64,
}

impl JsonMessage {
    /// A generic SimSage message class used throughout the system.  This class can be used to either send a success message (information) or an error message (error) but will never send you both at the same time.  Version might not always be set but is the version of the service-layer you're communicating with.
    pub fn new(error: String, information: String, version: String, time: i64) -> JsonMessage {
        JsonMessage {
            error,
            information,
            version,
            time,
        }
    }
}


