// tslint:disable
/**
 * SimSage REST API
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.11.4
 * Contact: info@simsage.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CMNewComment
 */
export interface CMNewComment {
    /**
     * @type {string}
     * @memberof CMNewComment
     */
    organisationId: string;
    /**
     * @type {string}
     * @memberof CMNewComment
     */
    projectId: string;
    /**
     * @type {string}
     * @memberof CMNewComment
     */
    sliceId: string;
    /**
     * @type {string}
     * @memberof CMNewComment
     */
    documentKey: string;
    /**
     * @type {string}
     * @memberof CMNewComment
     */
    commentLevel: string;
    /**
     * @type {string}
     * @memberof CMNewComment
     */
    comment: string;
}
