# coding: utf-8

"""
    SimSage REST API

    SimSage REST API

    The version of the OpenAPI document: 7.12.19
    Contact: info@simsage.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.knowledgebase_api import KnowledgebaseApi  # noqa: E501


class TestKnowledgebaseApi(unittest.TestCase):
    """KnowledgebaseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KnowledgebaseApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_export_knowledge_base(self) -> None:
        """Test case for export_knowledge_base

        export Knowledge-base  # noqa: E501
        """
        pass

    def test_get_knowledge_base(self) -> None:
        """Test case for get_knowledge_base

        Get Knowledge-base  # noqa: E501
        """
        pass

    def test_get_knowledge_bases(self) -> None:
        """Test case for get_knowledge_bases

        Get Knowledge-bases  # noqa: E501
        """
        pass

    def test_get_search_info(self) -> None:
        """Test case for get_search_info

        Search Info  # noqa: E501
        """
        pass

    def test_get_search_info2(self) -> None:
        """Test case for get_search_info2

        Search Info [deprecated]  # noqa: E501
        """
        pass

    def test_remove_knowledge_base(self) -> None:
        """Test case for remove_knowledge_base

        Delete Knowledge-base  # noqa: E501
        """
        pass

    def test_update_knowledge_base(self) -> None:
        """Test case for update_knowledge_base

        Save Knowledge-base  # noqa: E501
        """
        pass

    def test_version3(self) -> None:
        """Test case for version3

        Version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
