# coding: utf-8

"""
    SimSage REST API

    SimSage REST API

    The version of the OpenAPI document: 7.13.31
    Contact: info@simsage.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.crawler_api import CrawlerApi  # noqa: E501


class TestCrawlerApi(unittest.TestCase):
    """CrawlerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CrawlerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_crawler_delete_folder(self) -> None:
        """Test case for crawler_delete_folder

        Delete document folder  # noqa: E501
        """
        pass

    def test_crawler_delete_url(self) -> None:
        """Test case for crawler_delete_url

        Delete document  # noqa: E501
        """
        pass

    def test_crawler_external_document_delete(self) -> None:
        """Test case for crawler_external_document_delete

        Remove an External Document  # noqa: E501
        """
        pass

    def test_crawler_external_document_failed(self) -> None:
        """Test case for crawler_external_document_failed

        Upload External Document  # noqa: E501
        """
        pass

    def test_crawler_external_document_upload(self) -> None:
        """Test case for crawler_external_document_upload

        Upload External Document  # noqa: E501
        """
        pass

    def test_crawler_external_image_upload(self) -> None:
        """Test case for crawler_external_image_upload

        Upload External Image  # noqa: E501
        """
        pass

    def test_crawler_rename_folder(self) -> None:
        """Test case for crawler_rename_folder

        Rename document folder  # noqa: E501
        """
        pass

    def test_crawler_update_delta_token(self) -> None:
        """Test case for crawler_update_delta_token

        Update delta token  # noqa: E501
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete source  # noqa: E501
        """
        pass

    def test_delete_documents(self) -> None:
        """Test case for delete_documents

        Delete source's documents  # noqa: E501
        """
        pass

    def test_encrypted_communications(self) -> None:
        """Test case for encrypted_communications

        Secure Communication  # noqa: E501
        """
        pass

    def test_external_crawler(self) -> None:
        """Test case for external_crawler

        External Crawler  # noqa: E501
        """
        pass

    def test_external_crawler_finished(self) -> None:
        """Test case for external_crawler_finished

        Stop External Crawler  # noqa: E501
        """
        pass

    def test_external_crawler_start(self) -> None:
        """Test case for external_crawler_start

        Start External Crawler  # noqa: E501
        """
        pass

    def test_get_crawler(self) -> None:
        """Test case for get_crawler

        Get source  # noqa: E501
        """
        pass

    def test_get_failed_documents(self) -> None:
        """Test case for get_failed_documents

        Get source List  # noqa: E501
        """
        pass

    def test_get_source_list(self) -> None:
        """Test case for get_source_list

        Get source List  # noqa: E501
        """
        pass

    def test_mark_file_as_seen(self) -> None:
        """Test case for mark_file_as_seen

        Mark file as seen  # noqa: E501
        """
        pass

    def test_oidc_code(self) -> None:
        """Test case for oidc_code

        OIDC code receiver  # noqa: E501
        """
        pass

    def test_process_all_files(self) -> None:
        """Test case for process_all_files

        Process all files of crawler/source  # noqa: E501
        """
        pass

    def test_processor_schema(self) -> None:
        """Test case for processor_schema

        """
        pass

    def test_receive_external_log_entry(self) -> None:
        """Test case for receive_external_log_entry

        External Crawler log-entry  # noqa: E501
        """
        pass

    def test_reset_source_delta(self) -> None:
        """Test case for reset_source_delta

        Reset Source delta-token  # noqa: E501
        """
        pass

    def test_sdc_schema(self) -> None:
        """Test case for sdc_schema

        """
        pass

    def test_start_crawler(self) -> None:
        """Test case for start_crawler

        Start crawler  # noqa: E501
        """
        pass

    def test_test_crawler(self) -> None:
        """Test case for test_crawler

        Test Crawler  # noqa: E501
        """
        pass

    def test_update_crawler(self) -> None:
        """Test case for update_crawler

        Update Source  # noqa: E501
        """
        pass

    def test_version6(self) -> None:
        """Test case for version6

        Version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
