# coding: utf-8

"""
    SimSage REST API

    SimSage REST API

    The version of the OpenAPI document: 7.13.31
    Contact: info@simsage.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.cm_task_info import CMTaskInfo  # noqa: E501

class TestCMTaskInfo(unittest.TestCase):
    """CMTaskInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CMTaskInfo:
        """Test CMTaskInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CMTaskInfo`
        """
        model = CMTaskInfo()  # noqa: E501
        if include_optional:
            return CMTaskInfo(
                task_id = '',
                project_id = '',
                organisation_id = '',
                source_kb_id = '',
                crawler_kb_id = '',
                project_type = '',
                project_title = '',
                project_narrative = '',
                slice_id = '',
                process_id = '',
                process_name = '',
                task_type = '',
                task_name = '',
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_completed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                potential_users = '',
                excluded_users = '',
                potential_groups = '',
                assigned_user = ''
            )
        else:
            return CMTaskInfo(
                task_id = '',
                project_id = '',
                organisation_id = '',
                source_kb_id = '',
                project_type = '',
                project_title = '',
                project_narrative = '',
                process_id = '',
                process_name = '',
                task_type = '',
                task_name = '',
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                potential_users = '',
                excluded_users = '',
                potential_groups = '',
        )
        """

    def testCMTaskInfo(self):
        """Test CMTaskInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
