/*
 * SimSage REST API
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.14.12
 * Contact: info@simsage.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CMSearchTerm;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CMSearchDefinition
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-14T16:13:48.547313222+01:00[Europe/London]")
public class CMSearchDefinition {
  public static final String SERIALIZED_NAME_KEYED_QUERIES = "keyedQueries";
  @SerializedName(SERIALIZED_NAME_KEYED_QUERIES)
  private List<CMSearchTerm> keyedQueries = new ArrayList<>();

  public static final String SERIALIZED_NAME_SEMANTIC_TERM_QUERIES = "semanticTermQueries";
  @SerializedName(SERIALIZED_NAME_SEMANTIC_TERM_QUERIES)
  private List<CMSearchTerm> semanticTermQueries = new ArrayList<>();

  public CMSearchDefinition() {
  }

  public CMSearchDefinition keyedQueries(List<CMSearchTerm> keyedQueries) {
    
    this.keyedQueries = keyedQueries;
    return this;
  }

  public CMSearchDefinition addKeyedQueriesItem(CMSearchTerm keyedQueriesItem) {
    if (this.keyedQueries == null) {
      this.keyedQueries = new ArrayList<>();
    }
    this.keyedQueries.add(keyedQueriesItem);
    return this;
  }

   /**
   * Get keyedQueries
   * @return keyedQueries
  **/
  @javax.annotation.Nonnull
  public List<CMSearchTerm> getKeyedQueries() {
    return keyedQueries;
  }


  public void setKeyedQueries(List<CMSearchTerm> keyedQueries) {
    this.keyedQueries = keyedQueries;
  }


  public CMSearchDefinition semanticTermQueries(List<CMSearchTerm> semanticTermQueries) {
    
    this.semanticTermQueries = semanticTermQueries;
    return this;
  }

  public CMSearchDefinition addSemanticTermQueriesItem(CMSearchTerm semanticTermQueriesItem) {
    if (this.semanticTermQueries == null) {
      this.semanticTermQueries = new ArrayList<>();
    }
    this.semanticTermQueries.add(semanticTermQueriesItem);
    return this;
  }

   /**
   * Get semanticTermQueries
   * @return semanticTermQueries
  **/
  @javax.annotation.Nonnull
  public List<CMSearchTerm> getSemanticTermQueries() {
    return semanticTermQueries;
  }


  public void setSemanticTermQueries(List<CMSearchTerm> semanticTermQueries) {
    this.semanticTermQueries = semanticTermQueries;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CMSearchDefinition cmSearchDefinition = (CMSearchDefinition) o;
    return Objects.equals(this.keyedQueries, cmSearchDefinition.keyedQueries) &&
        Objects.equals(this.semanticTermQueries, cmSearchDefinition.semanticTermQueries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyedQueries, semanticTermQueries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CMSearchDefinition {\n");
    sb.append("    keyedQueries: ").append(toIndentedString(keyedQueries)).append("\n");
    sb.append("    semanticTermQueries: ").append(toIndentedString(semanticTermQueries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("keyedQueries");
    openapiFields.add("semanticTermQueries");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("keyedQueries");
    openapiRequiredFields.add("semanticTermQueries");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CMSearchDefinition
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CMSearchDefinition.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CMSearchDefinition is not found in the empty JSON string", CMSearchDefinition.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CMSearchDefinition.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CMSearchDefinition` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CMSearchDefinition.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("keyedQueries").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `keyedQueries` to be an array in the JSON string but got `%s`", jsonObj.get("keyedQueries").toString()));
      }

      JsonArray jsonArraykeyedQueries = jsonObj.getAsJsonArray("keyedQueries");
      // validate the required field `keyedQueries` (array)
      for (int i = 0; i < jsonArraykeyedQueries.size(); i++) {
        CMSearchTerm.validateJsonElement(jsonArraykeyedQueries.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("semanticTermQueries").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `semanticTermQueries` to be an array in the JSON string but got `%s`", jsonObj.get("semanticTermQueries").toString()));
      }

      JsonArray jsonArraysemanticTermQueries = jsonObj.getAsJsonArray("semanticTermQueries");
      // validate the required field `semanticTermQueries` (array)
      for (int i = 0; i < jsonArraysemanticTermQueries.size(); i++) {
        CMSearchTerm.validateJsonElement(jsonArraysemanticTermQueries.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CMSearchDefinition.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CMSearchDefinition' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CMSearchDefinition> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CMSearchDefinition.class));

       return (TypeAdapter<T>) new TypeAdapter<CMSearchDefinition>() {
           @Override
           public void write(JsonWriter out, CMSearchDefinition value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CMSearchDefinition read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CMSearchDefinition given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CMSearchDefinition
  * @throws IOException if the JSON string is invalid with respect to CMSearchDefinition
  */
  public static CMSearchDefinition fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CMSearchDefinition.class);
  }

 /**
  * Convert an instance of CMSearchDefinition to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

