/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.11.4
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMTextToSearchPaginated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMTextToSearchPaginatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMTextToSearchPaginated
        //private CMTextToSearchPaginated instance;

        public CMTextToSearchPaginatedTests()
        {
            // TODO uncomment below to create an instance of CMTextToSearchPaginated
            //instance = new CMTextToSearchPaginated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMTextToSearchPaginated
        /// </summary>
        [Fact]
        public void CMTextToSearchPaginatedInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMTextToSearchPaginated
            //Assert.IsType<CMTextToSearchPaginated>(instance);
        }

        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Fact]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }

        /// <summary>
        /// Test the property 'KbId'
        /// </summary>
        [Fact]
        public void KbIdTest()
        {
            // TODO unit test for the property 'KbId'
        }

        /// <summary>
        /// Test the property 'PrevWord'
        /// </summary>
        [Fact]
        public void PrevWordTest()
        {
            // TODO unit test for the property 'PrevWord'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
    }
}
