/*
 * SimSage REST API
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.13.31
 * Contact: info@simsage.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CMReturnStatistics
 */
public class CMReturnStatisticsTest {
    private final CMReturnStatistics model = new CMReturnStatistics();

    /**
     * Model tests for CMReturnStatistics
     */
    @Test
    public void testCMReturnStatistics() {
        // TODO: test CMReturnStatistics
    }

    /**
     * Test the property 'organisationId'
     */
    @Test
    public void organisationIdTest() {
        // TODO: test organisationId
    }

    /**
     * Test the property 'kbId'
     */
    @Test
    public void kbIdTest() {
        // TODO: test kbId
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'accessFrequency'
     */
    @Test
    public void accessFrequencyTest() {
        // TODO: test accessFrequency
    }

    /**
     * Test the property 'queryWordFrequency'
     */
    @Test
    public void queryWordFrequencyTest() {
        // TODO: test queryWordFrequency
    }

    /**
     * Test the property 'generalStatistics'
     */
    @Test
    public void generalStatisticsTest() {
        // TODO: test generalStatistics
    }

    /**
     * Test the property 'fileTypeStatistics'
     */
    @Test
    public void fileTypeStatisticsTest() {
        // TODO: test fileTypeStatistics
    }

}
