/*
 * SimSage REST API
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.14.12
 * Contact: info@simsage.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CMSearchTerm;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CMSearchDefinition
 */
public class CMSearchDefinitionTest {
    private final CMSearchDefinition model = new CMSearchDefinition();

    /**
     * Model tests for CMSearchDefinition
     */
    @Test
    public void testCMSearchDefinition() {
        // TODO: test CMSearchDefinition
    }

    /**
     * Test the property 'keyedQueries'
     */
    @Test
    public void keyedQueriesTest() {
        // TODO: test keyedQueries
    }

    /**
     * Test the property 'semanticTermQueries'
     */
    @Test
    public void semanticTermQueriesTest() {
        // TODO: test semanticTermQueries
    }

}
