/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.14.12
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMCommandQueueItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMCommandQueueItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMCommandQueueItem
        //private CMCommandQueueItem instance;

        public CMCommandQueueItemTests()
        {
            // TODO uncomment below to create an instance of CMCommandQueueItem
            //instance = new CMCommandQueueItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMCommandQueueItem
        /// </summary>
        [Fact]
        public void CMCommandQueueItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMCommandQueueItem
            //Assert.IsType<CMCommandQueueItem>(instance);
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Expiry'
        /// </summary>
        [Fact]
        public void ExpiryTest()
        {
            // TODO unit test for the property 'Expiry'
        }
    }
}
