/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.13.31
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMCrawlerStatusTask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMCrawlerStatusTaskTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMCrawlerStatusTask
        //private CMCrawlerStatusTask instance;

        public CMCrawlerStatusTaskTests()
        {
            // TODO uncomment below to create an instance of CMCrawlerStatusTask
            //instance = new CMCrawlerStatusTask();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMCrawlerStatusTask
        /// </summary>
        [Fact]
        public void CMCrawlerStatusTaskInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMCrawlerStatusTask
            //Assert.IsType<CMCrawlerStatusTask>(instance);
        }

        /// <summary>
        /// Test the property 'TaskInfo'
        /// </summary>
        [Fact]
        public void TaskInfoTest()
        {
            // TODO unit test for the property 'TaskInfo'
        }

        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
    }
}
