/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.12.19
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMCreateGdprProject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMCreateGdprProjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMCreateGdprProject
        //private CMCreateGdprProject instance;

        public CMCreateGdprProjectTests()
        {
            // TODO uncomment below to create an instance of CMCreateGdprProject
            //instance = new CMCreateGdprProject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMCreateGdprProject
        /// </summary>
        [Fact]
        public void CMCreateGdprProjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMCreateGdprProject
            //Assert.IsType<CMCreateGdprProject>(instance);
        }

        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Fact]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }

        /// <summary>
        /// Test the property 'KbId'
        /// </summary>
        [Fact]
        public void KbIdTest()
        {
            // TODO unit test for the property 'KbId'
        }

        /// <summary>
        /// Test the property 'ProjectDetails'
        /// </summary>
        [Fact]
        public void ProjectDetailsTest()
        {
            // TODO unit test for the property 'ProjectDetails'
        }
    }
}
