/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.11.4
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMDUserDashboard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMDUserDashboardTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMDUserDashboard
        //private CMDUserDashboard instance;

        public CMDUserDashboardTests()
        {
            // TODO uncomment below to create an instance of CMDUserDashboard
            //instance = new CMDUserDashboard();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMDUserDashboard
        /// </summary>
        [Fact]
        public void CMDUserDashboardInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMDUserDashboard
            //Assert.IsType<CMDUserDashboard>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'LockList'
        /// </summary>
        [Fact]
        public void LockListTest()
        {
            // TODO unit test for the property 'LockList'
        }

        /// <summary>
        /// Test the property 'BookmarkList'
        /// </summary>
        [Fact]
        public void BookmarkListTest()
        {
            // TODO unit test for the property 'BookmarkList'
        }

        /// <summary>
        /// Test the property 'Subscriptions'
        /// </summary>
        [Fact]
        public void SubscriptionsTest()
        {
            // TODO unit test for the property 'Subscriptions'
        }

        /// <summary>
        /// Test the property 'NotificationList'
        /// </summary>
        [Fact]
        public void NotificationListTest()
        {
            // TODO unit test for the property 'NotificationList'
        }

        /// <summary>
        /// Test the property 'FolderRoot'
        /// </summary>
        [Fact]
        public void FolderRootTest()
        {
            // TODO unit test for the property 'FolderRoot'
        }

        /// <summary>
        /// Test the property 'SavedSearchList'
        /// </summary>
        [Fact]
        public void SavedSearchListTest()
        {
            // TODO unit test for the property 'SavedSearchList'
        }

        /// <summary>
        /// Test the property 'CategoryList'
        /// </summary>
        [Fact]
        public void CategoryListTest()
        {
            // TODO unit test for the property 'CategoryList'
        }

        /// <summary>
        /// Test the property 'UserList'
        /// </summary>
        [Fact]
        public void UserListTest()
        {
            // TODO unit test for the property 'UserList'
        }

        /// <summary>
        /// Test the property 'GroupList'
        /// </summary>
        [Fact]
        public void GroupListTest()
        {
            // TODO unit test for the property 'GroupList'
        }
    }
}
