/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.12.19
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMExternalCrawlerDeleteFolder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMExternalCrawlerDeleteFolderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMExternalCrawlerDeleteFolder
        //private CMExternalCrawlerDeleteFolder instance;

        public CMExternalCrawlerDeleteFolderTests()
        {
            // TODO uncomment below to create an instance of CMExternalCrawlerDeleteFolder
            //instance = new CMExternalCrawlerDeleteFolder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMExternalCrawlerDeleteFolder
        /// </summary>
        [Fact]
        public void CMExternalCrawlerDeleteFolderInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMExternalCrawlerDeleteFolder
            //Assert.IsType<CMExternalCrawlerDeleteFolder>(instance);
        }

        /// <summary>
        /// Test the property 'ObjectType'
        /// </summary>
        [Fact]
        public void ObjectTypeTest()
        {
            // TODO unit test for the property 'ObjectType'
        }

        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Fact]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }

        /// <summary>
        /// Test the property 'KbId'
        /// </summary>
        [Fact]
        public void KbIdTest()
        {
            // TODO unit test for the property 'KbId'
        }

        /// <summary>
        /// Test the property 'Sid'
        /// </summary>
        [Fact]
        public void SidTest()
        {
            // TODO unit test for the property 'Sid'
        }

        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Fact]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }

        /// <summary>
        /// Test the property 'FolderUrl'
        /// </summary>
        [Fact]
        public void FolderUrlTest()
        {
            // TODO unit test for the property 'FolderUrl'
        }

        /// <summary>
        /// Test the property 'Encrypted'
        /// </summary>
        [Fact]
        public void EncryptedTest()
        {
            // TODO unit test for the property 'Encrypted'
        }

        /// <summary>
        /// Test the property 'Seed'
        /// </summary>
        [Fact]
        public void SeedTest()
        {
            // TODO unit test for the property 'Seed'
        }
    }
}
