/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.14.12
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMFailedSourceDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMFailedSourceDocumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMFailedSourceDocument
        //private CMFailedSourceDocument instance;

        public CMFailedSourceDocumentTests()
        {
            // TODO uncomment below to create an instance of CMFailedSourceDocument
            //instance = new CMFailedSourceDocument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMFailedSourceDocument
        /// </summary>
        [Fact]
        public void CMFailedSourceDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMFailedSourceDocument
            //Assert.IsType<CMFailedSourceDocument>(instance);
        }

        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Fact]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }

        /// <summary>
        /// Test the property 'KbId'
        /// </summary>
        [Fact]
        public void KbIdTest()
        {
            // TODO unit test for the property 'KbId'
        }

        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Fact]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }

        /// <summary>
        /// Test the property 'SourceSystemId'
        /// </summary>
        [Fact]
        public void SourceSystemIdTest()
        {
            // TODO unit test for the property 'SourceSystemId'
        }

        /// <summary>
        /// Test the property 'WebUrl'
        /// </summary>
        [Fact]
        public void WebUrlTest()
        {
            // TODO unit test for the property 'WebUrl'
        }

        /// <summary>
        /// Test the property 'DeltaRootId'
        /// </summary>
        [Fact]
        public void DeltaRootIdTest()
        {
            // TODO unit test for the property 'DeltaRootId'
        }

        /// <summary>
        /// Test the property 'RunId'
        /// </summary>
        [Fact]
        public void RunIdTest()
        {
            // TODO unit test for the property 'RunId'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

        /// <summary>
        /// Test the property 'Encrypted'
        /// </summary>
        [Fact]
        public void EncryptedTest()
        {
            // TODO unit test for the property 'Encrypted'
        }

        /// <summary>
        /// Test the property 'Seed'
        /// </summary>
        [Fact]
        public void SeedTest()
        {
            // TODO unit test for the property 'Seed'
        }

        /// <summary>
        /// Test the property 'Sid'
        /// </summary>
        [Fact]
        public void SidTest()
        {
            // TODO unit test for the property 'Sid'
        }
    }
}
