/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.14.12
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMImportUsers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMImportUsersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMImportUsers
        //private CMImportUsers instance;

        public CMImportUsersTests()
        {
            // TODO uncomment below to create an instance of CMImportUsers
            //instance = new CMImportUsers();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMImportUsers
        /// </summary>
        [Fact]
        public void CMImportUsersInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMImportUsers
            //Assert.IsType<CMImportUsers>(instance);
        }

        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Fact]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }

        /// <summary>
        /// Test the property 'FileType'
        /// </summary>
        [Fact]
        public void FileTypeTest()
        {
            // TODO unit test for the property 'FileType'
        }

        /// <summary>
        /// Test the property 'Base64Text'
        /// </summary>
        [Fact]
        public void Base64TextTest()
        {
            // TODO unit test for the property 'Base64Text'
        }
    }
}
