/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.11.4
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMParquetTimeList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMParquetTimeListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMParquetTimeList
        //private CMParquetTimeList instance;

        public CMParquetTimeListTests()
        {
            // TODO uncomment below to create an instance of CMParquetTimeList
            //instance = new CMParquetTimeList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMParquetTimeList
        /// </summary>
        [Fact]
        public void CMParquetTimeListInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMParquetTimeList
            //Assert.IsType<CMParquetTimeList>(instance);
        }

        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Fact]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }

        /// <summary>
        /// Test the property 'KbId'
        /// </summary>
        [Fact]
        public void KbIdTest()
        {
            // TODO unit test for the property 'KbId'
        }

        /// <summary>
        /// Test the property 'TimeList'
        /// </summary>
        [Fact]
        public void TimeListTest()
        {
            // TODO unit test for the property 'TimeList'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }
    }
}
