/*
 * SimSage REST API
 *
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.12.19
 * Contact: info@simsage.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CMProjectDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMProjectDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMProjectDefinition
        //private CMProjectDefinition instance;

        public CMProjectDefinitionTests()
        {
            // TODO uncomment below to create an instance of CMProjectDefinition
            //instance = new CMProjectDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMProjectDefinition
        /// </summary>
        [Fact]
        public void CMProjectDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMProjectDefinition
            //Assert.IsType<CMProjectDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }

        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Fact]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }

        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Fact]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }

        /// <summary>
        /// Test the property 'ProjectFrame'
        /// </summary>
        [Fact]
        public void ProjectFrameTest()
        {
            // TODO unit test for the property 'ProjectFrame'
        }

        /// <summary>
        /// Test the property 'KeyedSearchTerms'
        /// </summary>
        [Fact]
        public void KeyedSearchTermsTest()
        {
            // TODO unit test for the property 'KeyedSearchTerms'
        }

        /// <summary>
        /// Test the property 'SemanticTerms'
        /// </summary>
        [Fact]
        public void SemanticTermsTest()
        {
            // TODO unit test for the property 'SemanticTerms'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'ValidationResult'
        /// </summary>
        [Fact]
        public void ValidationResultTest()
        {
            // TODO unit test for the property 'ValidationResult'
        }
    }
}
