/*
 * SimSage REST API
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.11.4
 * Contact: info@simsage.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * A SimSage category is a metadata description in SimSage.  This object represents a single piece of categorical data that is uploaded to SimSage from external sources as part of a CMDocumentUpload request.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-16T13:18:33.437170740+01:00[Europe/London]")
public class MDCategory {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_DISPLAY = "display";
  @SerializedName(SERIALIZED_NAME_DISPLAY)
  private String display;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private String metadata;

  public static final String SERIALIZED_NAME_STRING_VALUE_LIST = "stringValueList";
  @SerializedName(SERIALIZED_NAME_STRING_VALUE_LIST)
  private String stringValueList;

  public static final String SERIALIZED_NAME_NUMBER_VALUE_LIST = "numberValueList";
  @SerializedName(SERIALIZED_NAME_NUMBER_VALUE_LIST)
  private String numberValueList;

  public static final String SERIALIZED_NAME_SORT = "sort";
  @SerializedName(SERIALIZED_NAME_SORT)
  private Boolean sort;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private Integer order;

  public static final String SERIALIZED_NAME_SORT_DEFAULT = "sortDefault";
  @SerializedName(SERIALIZED_NAME_SORT_DEFAULT)
  private String sortDefault;

  public static final String SERIALIZED_NAME_SORT_ASC_TEXT = "sortAscText";
  @SerializedName(SERIALIZED_NAME_SORT_ASC_TEXT)
  private String sortAscText;

  public static final String SERIALIZED_NAME_SORT_DESC_TEXT = "sortDescText";
  @SerializedName(SERIALIZED_NAME_SORT_DESC_TEXT)
  private String sortDescText;

  public MDCategory() {
  }

  public MDCategory key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * The SimSage type of category
   * @return key
  **/
  @javax.annotation.Nonnull
  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public MDCategory display(String display) {
    
    this.display = display;
    return this;
  }

   /**
   * A friendly display name for any UI component rendering this component
   * @return display
  **/
  @javax.annotation.Nonnull
  public String getDisplay() {
    return display;
  }


  public void setDisplay(String display) {
    this.display = display;
  }


  public MDCategory metadata(String metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * The metadata-name inside SimSage for this item.  Only a..z A..Z 0..9 and - are allowed as characters in this string.
   * @return metadata
  **/
  @javax.annotation.Nonnull
  public String getMetadata() {
    return metadata;
  }


  public void setMetadata(String metadata) {
    this.metadata = metadata;
  }


  public MDCategory stringValueList(String stringValueList) {
    
    this.stringValueList = stringValueList;
    return this;
  }

   /**
   * A list of string values (if string based) for this metadata category item.  These are the values this document \&quot;belongs to\&quot;
   * @return stringValueList
  **/
  @javax.annotation.Nonnull
  public String getStringValueList() {
    return stringValueList;
  }


  public void setStringValueList(String stringValueList) {
    this.stringValueList = stringValueList;
  }


  public MDCategory numberValueList(String numberValueList) {
    
    this.numberValueList = numberValueList;
    return this;
  }

   /**
   * Alternatively, a list of numeric values (if number based) for this metadata category item.  These are the values this document \&quot;belongs to\&quot;
   * @return numberValueList
  **/
  @javax.annotation.Nonnull
  public String getNumberValueList() {
    return numberValueList;
  }


  public void setNumberValueList(String numberValueList) {
    this.numberValueList = numberValueList;
  }


  public MDCategory sort(Boolean sort) {
    
    this.sort = sort;
    return this;
  }

   /**
   * Is this category to be sort-able in the UI?
   * @return sort
  **/
  @javax.annotation.Nonnull
  public Boolean getSort() {
    return sort;
  }


  public void setSort(Boolean sort) {
    this.sort = sort;
  }


  public MDCategory order(Integer order) {
    
    this.order = order;
    return this;
  }

   /**
   * What order does this item have in the UI display?
   * @return order
  **/
  @javax.annotation.Nonnull
  public Integer getOrder() {
    return order;
  }


  public void setOrder(Integer order) {
    this.order = order;
  }


  public MDCategory sortDefault(String sortDefault) {
    
    this.sortDefault = sortDefault;
    return this;
  }

   /**
   * Is this item THE default sort item in the UI, and if so, is it ascending (asc) or descending (desc).  Not the default sort if empty.
   * @return sortDefault
  **/
  @javax.annotation.Nonnull
  public String getSortDefault() {
    return sortDefault;
  }


  public void setSortDefault(String sortDefault) {
    this.sortDefault = sortDefault;
  }


  public MDCategory sortAscText(String sortAscText) {
    
    this.sortAscText = sortAscText;
    return this;
  }

   /**
   * If sortable, what label should the UI display for ascending sort?
   * @return sortAscText
  **/
  @javax.annotation.Nonnull
  public String getSortAscText() {
    return sortAscText;
  }


  public void setSortAscText(String sortAscText) {
    this.sortAscText = sortAscText;
  }


  public MDCategory sortDescText(String sortDescText) {
    
    this.sortDescText = sortDescText;
    return this;
  }

   /**
   * If sortable, what label should the UI display for descending sort?
   * @return sortDescText
  **/
  @javax.annotation.Nonnull
  public String getSortDescText() {
    return sortDescText;
  }


  public void setSortDescText(String sortDescText) {
    this.sortDescText = sortDescText;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MDCategory mdCategory = (MDCategory) o;
    return Objects.equals(this.key, mdCategory.key) &&
        Objects.equals(this.display, mdCategory.display) &&
        Objects.equals(this.metadata, mdCategory.metadata) &&
        Objects.equals(this.stringValueList, mdCategory.stringValueList) &&
        Objects.equals(this.numberValueList, mdCategory.numberValueList) &&
        Objects.equals(this.sort, mdCategory.sort) &&
        Objects.equals(this.order, mdCategory.order) &&
        Objects.equals(this.sortDefault, mdCategory.sortDefault) &&
        Objects.equals(this.sortAscText, mdCategory.sortAscText) &&
        Objects.equals(this.sortDescText, mdCategory.sortDescText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, display, metadata, stringValueList, numberValueList, sort, order, sortDefault, sortAscText, sortDescText);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MDCategory {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    stringValueList: ").append(toIndentedString(stringValueList)).append("\n");
    sb.append("    numberValueList: ").append(toIndentedString(numberValueList)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    sortDefault: ").append(toIndentedString(sortDefault)).append("\n");
    sb.append("    sortAscText: ").append(toIndentedString(sortAscText)).append("\n");
    sb.append("    sortDescText: ").append(toIndentedString(sortDescText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("key");
    openapiFields.add("display");
    openapiFields.add("metadata");
    openapiFields.add("stringValueList");
    openapiFields.add("numberValueList");
    openapiFields.add("sort");
    openapiFields.add("order");
    openapiFields.add("sortDefault");
    openapiFields.add("sortAscText");
    openapiFields.add("sortDescText");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("key");
    openapiRequiredFields.add("display");
    openapiRequiredFields.add("metadata");
    openapiRequiredFields.add("stringValueList");
    openapiRequiredFields.add("numberValueList");
    openapiRequiredFields.add("sort");
    openapiRequiredFields.add("order");
    openapiRequiredFields.add("sortDefault");
    openapiRequiredFields.add("sortAscText");
    openapiRequiredFields.add("sortDescText");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to MDCategory
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MDCategory.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MDCategory is not found in the empty JSON string", MDCategory.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MDCategory.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MDCategory` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MDCategory.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
      if (!jsonObj.get("display").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `display` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display").toString()));
      }
      if (!jsonObj.get("metadata").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `metadata` to be a primitive type in the JSON string but got `%s`", jsonObj.get("metadata").toString()));
      }
      if (!jsonObj.get("stringValueList").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stringValueList` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stringValueList").toString()));
      }
      if (!jsonObj.get("numberValueList").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `numberValueList` to be a primitive type in the JSON string but got `%s`", jsonObj.get("numberValueList").toString()));
      }
      if (!jsonObj.get("sortDefault").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sortDefault` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sortDefault").toString()));
      }
      if (!jsonObj.get("sortAscText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sortAscText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sortAscText").toString()));
      }
      if (!jsonObj.get("sortDescText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sortDescText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sortDescText").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MDCategory.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MDCategory' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MDCategory> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MDCategory.class));

       return (TypeAdapter<T>) new TypeAdapter<MDCategory>() {
           @Override
           public void write(JsonWriter out, MDCategory value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MDCategory read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MDCategory given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MDCategory
  * @throws IOException if the JSON string is invalid with respect to MDCategory
  */
  public static MDCategory fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MDCategory.class);
  }

 /**
  * Convert an instance of MDCategory to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

