/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * the document hash-tag object.  A list of hash-tags.  Each hash-tag must start with a '#' and only contain a..z,A..Z.  Minimum size 3 characters, maximum size 50 characters.
 *
 * @param organisationId the main organisation (its guid id) for this source/crawler
 * @param kbId the knowledge-base id of this context item, a guid-string
 * @param url The unique URL of a document.
 * @param hashTagList a list of hash-tags for this document
 */


data class CMDocumentHashTag (

    /* the main organisation (its guid id) for this source/crawler */
    @Json(name = "organisationId")
    val organisationId: kotlin.String,

    /* the knowledge-base id of this context item, a guid-string */
    @Json(name = "kbId")
    val kbId: kotlin.String,

    /* The unique URL of a document. */
    @Json(name = "url")
    val url: kotlin.String,

    /* a list of hash-tags for this document */
    @Json(name = "hashTagList")
    val hashTagList: kotlin.collections.List<kotlin.String>

)

