/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A document Access Control List (ACL) item.  This item represents a user's/group's access to a document (hasAccess or not).
 *
 * @param acl Some acl value, can represent a user's email address or the name of a remote security-group.
 * @param access is this ACL allowing access (Read/Write/Delete/Modify (RWDM)) or denying access (empty)
 * @param isUser \"true\" if this a security-user (email address), \"false\" if this ACL pertains to a security-group (group name)
 * @param user 
 */


data class CMDocumentAcl (

    /* Some acl value, can represent a user's email address or the name of a remote security-group. */
    @Json(name = "acl")
    val acl: kotlin.String,

    /* is this ACL allowing access (Read/Write/Delete/Modify (RWDM)) or denying access (empty) */
    @Json(name = "access")
    val access: kotlin.String,

    /* \"true\" if this a security-user (email address), \"false\" if this ACL pertains to a security-group (group name) */
    @Json(name = "isUser")
    val isUser: kotlin.Boolean,

    @Json(name = "user")
    val user: kotlin.Boolean? = null

)

