/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A security-group object.  Groups can contain security users and are used to group/clump users.
 *
 * @param organisationId the organisation (its guid id) this group is associated with
 * @param name the name of this group
 * @param originalName the original-name of this group to help rename the group
 * @param userIdList a list of user-ids (can be empty) part of this group
 */


data class CMGroup (

    /* the organisation (its guid id) this group is associated with */
    @Json(name = "organisationId")
    val organisationId: kotlin.String,

    /* the name of this group */
    @Json(name = "name")
    val name: kotlin.String,

    /* the original-name of this group to help rename the group */
    @Json(name = "originalName")
    val originalName: kotlin.String,

    /* a list of user-ids (can be empty) part of this group */
    @Json(name = "userIdList")
    val userIdList: kotlin.collections.List<kotlin.String>

)

