/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CMSemantic

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A paginated semantics return list matching a request for the same.
 *
 * @param organisationId the organisation (its guid id).
 * @param kbId the knowledge-base (its guid id).
 * @param filter The filter that was used to find these items.
 * @param semanticList the resulting list of semantics (return)
 * @param numSemantics the total number of semantics that matched.
 */


data class CMSemanticsPaginatedResult (

    /* the organisation (its guid id). */
    @Json(name = "organisationId")
    val organisationId: kotlin.String,

    /* the knowledge-base (its guid id). */
    @Json(name = "kbId")
    val kbId: kotlin.String,

    /* The filter that was used to find these items. */
    @Json(name = "filter")
    val filter: kotlin.String,

    /* the resulting list of semantics (return) */
    @Json(name = "semanticList")
    val semanticList: kotlin.collections.List<CMSemantic>,

    /* the total number of semantics that matched. */
    @Json(name = "numSemantics")
    val numSemantics: kotlin.Int

)

