/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CMPagedResultsCMSlicedDocument

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param pagedResults 
 * @param allDocs 
 * @param completed 
 * @param sourceMap 
 * @param userMap 
 */


data class CMSlicedDocumentListAndTotals (

    @Json(name = "pagedResults")
    val pagedResults: CMPagedResultsCMSlicedDocument,

    @Json(name = "allDocs")
    val allDocs: kotlin.Long,

    @Json(name = "completed")
    val completed: kotlin.Long,

    @Json(name = "sourceMap")
    val sourceMap: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "userMap")
    val userMap: kotlin.collections.Map<kotlin.String, kotlin.String>

)

