/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Source base-info represents information needed by external UI systems interacting with SimSage.  This object has information pertaining to a source in SimSage.  Its name, id, what sort of a source it is, and what sort of security integration (if any) this source has.  This object is contained inside a CMKnowledgeBaseInfo object.
 *
 * @param name the name of this source
 * @param sourceId the id of this source
 * @param sourceType the type of this source
 * @param customRender Does this source require custom render templates or use ordinary search-results?
 */


data class CMSourceBaseInfo (

    /* the name of this source */
    @Json(name = "name")
    val name: kotlin.String,

    /* the id of this source */
    @Json(name = "sourceId")
    val sourceId: kotlin.Int,

    /* the type of this source */
    @Json(name = "sourceType")
    val sourceType: kotlin.String,

    /* Does this source require custom render templates or use ordinary search-results? */
    @Json(name = "customRender")
    val customRender: kotlin.Boolean

)

