/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TextToSearch

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A set of paginated text-to-search objects for a given organisation/knowledge-base with a total count.
 *
 * @param textToSearchList a list of text-to-search items
 * @param numTextToSearch the total number of text-to-search items
 */


data class CMTextToSearchPaginatedReturn (

    /* a list of text-to-search items */
    @Json(name = "textToSearchList")
    val textToSearchList: kotlin.collections.List<TextToSearch>,

    /* the total number of text-to-search items */
    @Json(name = "numTextToSearch")
    val numTextToSearch: kotlin.Int

)

