// tslint:disable
/**
 * SimSage REST API
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.12.19
 * Contact: info@simsage.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface KnowledgeBase
 */
export interface KnowledgeBase {
    /**
     * @type {string}
     * @memberof KnowledgeBase
     */
    kbId: string;
    /**
     * @type {string}
     * @memberof KnowledgeBase
     */
    organisationId: string;
    /**
     * @type {string}
     * @memberof KnowledgeBase
     */
    name: string;
    /**
     * @type {string}
     * @memberof KnowledgeBase
     */
    email: string;
    /**
     * @type {string}
     * @memberof KnowledgeBase
     */
    securityId: string;
    /**
     * @type {number}
     * @memberof KnowledgeBase
     */
    created: number;
    /**
     * @type {number}
     * @memberof KnowledgeBase
     */
    maxQueriesPerDay: number;
    /**
     * @type {number}
     * @memberof KnowledgeBase
     */
    analyticsWindowInMonths: number;
    /**
     * @type {boolean}
     * @memberof KnowledgeBase
     */
    enabled: boolean;
    /**
     * @type {boolean}
     * @memberof KnowledgeBase
     */
    operatorEnabled: boolean;
    /**
     * @type {boolean}
     * @memberof KnowledgeBase
     */
    capacityWarnings: boolean;
    /**
     * @type {string}
     * @memberof KnowledgeBase
     */
    indexSchedule: string;
    /**
     * @type {number}
     * @memberof KnowledgeBase
     */
    lastIndexOptimizationTime: number;
    /**
     * @type {boolean}
     * @memberof KnowledgeBase
     */
    projectKb: boolean;
}
