/*
 * SimSage REST API
 * SimSage REST API
 *
 * The version of the OpenAPI document: 7.11.4
 * Contact: info@simsage.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Backup;
import org.openapitools.client.model.CMRestoreFromText;
import org.openapitools.client.model.JsonMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BackupApi
 */
@Disabled
public class BackupApiTest {

    private final BackupApi api = new BackupApi();

    /**
     * create backup
     *
     * Backup all of SimSage (excludes indexes and documents).  Create a SimSage text file with all relevant information for a SimSage Restore on the cloud node.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void backupTest() throws ApiException {
        String sessionId = null;
        String organisationId = null;
        String regime = null;
        JsonMessage response = api.backup(sessionId, organisationId, regime);
        // TODO: test validations
    }

    /**
     * remove backup
     *
     * Delete a backup by ID and return list of all Backups present in this SimSage instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteBackupTest() throws ApiException {
        String sessionId = null;
        String organisationId = null;
        Long backupId = null;
        List<Backup> response = api.deleteBackup(sessionId, organisationId, backupId);
        // TODO: test validations
    }

    /**
     * get backup
     *
     * return the backup data for a given backup-id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBackupTest() throws ApiException {
        String sessionId = null;
        String organisationId = null;
        Long backupId = null;
        Backup response = api.getBackup(sessionId, organisationId, backupId);
        // TODO: test validations
    }

    /**
     * get backup list
     *
     * Get a list of all Backups present in this SimSage instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBackupListTest() throws ApiException {
        String sessionId = null;
        String organisationId = null;
        List<Backup> response = api.getBackupList(sessionId, organisationId);
        // TODO: test validations
    }

    /**
     * restore backup
     *
     * Restore parts of SimSage (documents, users, organisation/kb, roles) from a text-file.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void restoreFromTextTest() throws ApiException {
        String sessionId = null;
        CMRestoreFromText cmRestoreFromText = null;
        JsonMessage response = api.restoreFromText(sessionId, cmRestoreFromText);
        // TODO: test validations
    }

}
