# coding: utf-8

"""
    SimSage REST API

    SimSage REST API

    The version of the OpenAPI document: 7.11.4
    Contact: info@simsage.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class CMCategorization(BaseModel):
    """
    A categorization object.  # noqa: E501
    """
    organisation_id: StrictStr = Field(..., alias="organisationId", description="the organisation (its guid id)")
    kb_id: StrictStr = Field(..., alias="kbId", description="the knowledge-base (its guid id)")
    categorization_label: StrictStr = Field(..., alias="categorizationLabel", description="the categorization label (the value field) for a categorization")
    rule: StrictStr = Field(..., description="the SimSage SuperSearch rule to match for adding this categorization label to a document")
    __properties = ["organisationId", "kbId", "categorizationLabel", "rule"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CMCategorization:
        """Create an instance of CMCategorization from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CMCategorization:
        """Create an instance of CMCategorization from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CMCategorization.parse_obj(obj)

        _obj = CMCategorization.parse_obj({
            "organisation_id": obj.get("organisationId"),
            "kb_id": obj.get("kbId"),
            "categorization_label": obj.get("categorizationLabel"),
            "rule": obj.get("rule")
        })
        return _obj


