# coding: utf-8

"""
    SimSage REST API

    SimSage REST API

    The version of the OpenAPI document: 7.13.31
    Contact: info@simsage.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

class DocumentBookmark(BaseModel):
    """
    DocumentBookmark
    """
    user_id: StrictStr = Field(..., alias="userId")
    source_id: StrictInt = Field(..., alias="sourceId")
    url: StrictStr = Field(...)
    url_id: StrictInt = Field(..., alias="urlId")
    is_folder: StrictBool = Field(..., alias="isFolder")
    folder: Optional[StrictBool] = None
    __properties = ["userId", "sourceId", "url", "urlId", "isFolder", "folder"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DocumentBookmark:
        """Create an instance of DocumentBookmark from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DocumentBookmark:
        """Create an instance of DocumentBookmark from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DocumentBookmark.parse_obj(obj)

        _obj = DocumentBookmark.parse_obj({
            "user_id": obj.get("userId"),
            "source_id": obj.get("sourceId"),
            "url": obj.get("url"),
            "url_id": obj.get("urlId"),
            "is_folder": obj.get("isFolder"),
            "folder": obj.get("folder")
        })
        return _obj


